version: "3.9"
services:
  portfolio:
    image: "nginx:${IMAGE_TAG:-1.21.5-alpine}"
    container_name: aunlead-portfolio
    depends_on:
      - watchtower
      - traefik
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.portfolio.rule=Host(`${HOST_URL}`) || Host(`${HOST_URL_2}`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data/content:/usr/share/nginx/html:ro"
    environment:
      - NODE_ENV=production
      - url=https://${HOST_URL}
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
